character = {
    "attack_strength": 10,
    "dead": false,
    "found_love": false,
    "items": {
              "ax": 0,
              "black_mushroom": 0,
              "bottle_of_sap": 0,
              "bottle_of_void_dust": 0,
              "fireproof_cloak": 0,
              "flowers": 0,
              "frog": 0,
              "cat": 0,
              "clover": 0,
              "crisp": 0,
              "cutlass": 0,
              "dagger": 0,
              "deep_cave_newt": 0,
              "fish": 0,
              "hammer": 0,
              "iron_hammer": 0,
              "jewels": 0,
              "jeweled_cutlass": 0,
              "long_pitchfork": 0,
              "love_potion": 0,
              "many_colored_mushroom": 0,
              "pearl": 0,
              "pitchfork": 0,
              "poison_dagger": 0,
              "sailor_peg": 0,
              "seal carcass": 0,
              "shiny_coin": 0,
              "strength_potion": 0,
              "tail_potion": 0,
              "white_mushroom": 0,
              "yellow_mushroom": 0,
    }, 
    "money": "no money",
    "moved": false,
    "person": null,
    "place": "tavern",
    "threatened": false,
};
