"use strict";

exports.character = {
    "excuse": "",
    "has_found_true_love": false,
    "is_dead": false,
    "is_frog": false,
    "is_monstrosity": false,
    "is_threatened": false,
    "is_tripping": false,
    "items": 
    {
        "dagger": 0,
        "cutlass": 0,
        "hammer": 0,
        "iron_hammer": 0,
        "jeweled_cutlass": 0,
        "long_pitchfork": 0,
        "pitchfork": 0,
        "poison_dagger": 0,

        "ax": 1,
        "bag of jewels": 0,
        "ball of sap": 0,
        "black mushroom": 0,
        "bouquet of flowers": 0,
        "cat": 1,
        "deep-cave newt": 0,
        "fancy red cloak": 0,
        "fish": 0,
        "four-leaf clover": 0,
        "frog": 1,
        "handful of void dust": 0,
        "many colored mushroom": 0,
        "pearl": 0,
        "potion of love": 1,
        "potion of strength": 0,
        "potion of tail growth": 0,
        "sailor peg": 0,
        "seal carcass": 0,
        "shiny foreign coin": 0,
        "white mushroom": 0,
        "yellow mushroom": 1,
    },
    "money": "none",
    "person": "",
    "place": "tavern",
    "score": 0,
    "strength": 0
}
